// react/react-jest-test/src/components/MyInput.tsx
import React, { useState } from 'react'

function MyInput() {
  const [name, setName] = useState('')
  return (
    <div>
      <input
        value={name}
        placeholder='请输入名字'
        onChange={e => setName(e.target.value)}
      />
      <p>
        this is my name: <span>{name}</span>
      </p>
    </div>
  )
}

export { MyInput }

// vue3/vue3-render-examples/src/components/MyInput.jsx
import { h, ref } from 'vue'
export default {
  name: 'MyInput',
  setup() {
    const inputText = ref('jack')
    const onInput = ({ target }) => {
      inputText.value = target.value
    }
    return {
      inputText,
      onInput,
    }
  },
  render() {
    // return (
    //   <div>
    //     {/* NOTE 不再支持 */}
    //     <input vModel={this.inputText} />
    //     <h2>{this.inputText}</h2>
    //   </div>
    // )
    return (
      <div>
        <input value={this.inputText} onInput={this.onInput} />
        <h2>{this.inputText}</h2>
      </div>
    )
    // return h('div', null, [
    //   h('input', {
    //     // NOTE model 不再支持
    //     // model: {
    //     //   value: this.inputText,
    //     // },
    //     value: this.inputText,
    //     onInput: this.onInput,
    //   }),
    //   h('h2', this.inputText),
    // ])
  },
}
